#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
share_drive_compare.py

Build SHOULD-HAVE vs DOES-HAVE comparison for SHARE DRIVE access.

Primary API:
    build_share_drive_should_vs_does_report(...)

Optional CLI:
    python share_drive_compare.py --shd-have "..." --hr "..." --does-have "..." --out "output.xlsx"

Author: Generated by ChatGPT
"""

import re
import argparse
from typing import Any, Dict, List, Optional, Tuple
import pandas as pd


def build_share_drive_should_vs_does_report(
    shd_have_xlsx: str,
    hr_xlsx: str,
    does_have_access_file: str,
    out_xlsx: Optional[str] = None,
    # ---------- SHOULD HAVE ----------
    shd_sheet_filter_contains: Optional[str] = None,
    shd_persona_col: str = "PERSONA",
    shd_entitlement_col_candidates: Tuple[str, ...] = ("ENTITLEMENTS", "PERMISSION"),
    # ---------- HR / PERSONA MAP ----------
    hr_costcenter_col: str = "COST CENTER - ID",
    hr_mgmt_level_col: str = "MANAGEMENT LEVEL",
    hr_persona_out_col: str = "SUGGESTED PERSONA",
    costcenter_persona_map_xlsx: Optional[str] = None,
    costcenter_persona_map_sheet: Optional[str] = None,
    map_costcenter_col: str = "COSTCENTER_MANAGEMENT-LEVEL",
    map_persona_col: str = "PERSONA",
    # ---------- DOES HAVE ----------
    does_have_brid_col: str = "BRID",
    does_have_share_drive_col_candidates: Tuple[str, ...] = (
        "SHARE DRIVE DISPLAY NAME",
        "SHARE DRIVE NAME",
        "ENTITLEMENT",
        "PERMISSION",
    ),
    does_have_delimiter: str = "|",
) -> pd.DataFrame:

    # ---------------- helpers ----------------
    def _upper_strip_cols(df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        df.columns = [str(c).strip().upper() for c in df.columns]
        return df

    def _safe_str(x: Any) -> str:
        if x is None or (isinstance(x, float) and pd.isna(x)):
            return ""
        return str(x)

    def _normalize_path(x: Any) -> str:
        s = _safe_str(x).strip().strip('"').strip("'")
        s = s.replace("/", "\\")
        s = re.sub(r"\\{2,}", r"\\", s)
        s = s.rstrip("\\")
        return s.upper()

    def _extract_y_drive(text: Any) -> str:
        s = _safe_str(text)
        m = re.search(r"(Y:\\\\.*?)(?=,|\\n|\\r|$)", s, flags=re.IGNORECASE)
        return _normalize_path(m.group(1)) if m else ""

    def _split(cell: Any) -> List[str]:
        s = _safe_str(cell)
        if not s.strip():
            return []
        parts = re.split(r"[\\n\\r,;|]+", s)
        return [_normalize_path(p) for p in parts if p.strip()]

    def _pick(df_cols: List[str], candidates: Tuple[str, ...]) -> Optional[str]:
        for c in candidates:
            if c.upper() in df_cols:
                return c.upper()
        return None

    def _build_dict(df: pd.DataFrame, key_col: str, val_col: str) -> Dict[str, set]:
        d: Dict[str, set] = {}
        for k, sub in df.groupby(key_col):
            s = set()
            for v in sub[val_col]:
                extracted = _extract_y_drive(v)
                if extracted:
                    s.add(extracted)
                else:
                    s.update(_split(v))
            d[str(k)] = s
        return d

    def _compare(does: set, shd: set):
        return (
            sorted(list(does & shd)),
            sorted(list(shd - does)),
            sorted(list(does - shd)),
        )

    # ---------------- SHOULD HAVE ----------------
    xls = pd.ExcelFile(shd_have_xlsx)
    sheets = xls.sheet_names
    if shd_sheet_filter_contains:
        sheets = [s for s in sheets if shd_sheet_filter_contains.upper() in s.upper()]

    shd_frames = []
    for sh in sheets:
        df = pd.read_excel(shd_have_xlsx, sheet_name=sh)
        df = _upper_strip_cols(df)
        if shd_persona_col.upper() in df.columns:
            df[shd_persona_col.upper()] = df[shd_persona_col.upper()].map(_normalize_path)
        df["SHEET_NAME"] = sh
        shd_frames.append(df)

    df_shd = pd.concat(shd_frames, ignore_index=True)
    ent_col = _pick(df_shd.columns.tolist(), shd_entitlement_col_candidates)
    if not ent_col:
        raise ValueError("No entitlement/permission column found in SHOULD-HAVE file")

    shd_map = _build_dict(df_shd, shd_persona_col.upper(), ent_col)

    # ---------------- DOES HAVE ----------------
    df_does = pd.read_csv(does_have_access_file, sep=does_have_delimiter, engine="python", dtype=str)
    df_does = _upper_strip_cols(df_does)

    brid_u = does_have_brid_col.upper()
    drive_col = _pick(df_does.columns.tolist(), does_have_share_drive_col_candidates)
    if not drive_col:
        raise ValueError("No share-drive column found in DOES-HAVE file")

    df_does[brid_u] = df_does[brid_u].map(_normalize_path)
    does_map = _build_dict(df_does, brid_u, drive_col)

    # ---------------- HR + PERSONA ----------------
    df_hr = pd.read_excel(hr_xlsx)
    df_hr = _upper_strip_cols(df_hr)

    cc_u, ml_u = hr_costcenter_col.upper(), hr_mgmt_level_col.upper()
    out_p_u = hr_persona_out_col.upper()

    if costcenter_persona_map_xlsx:
        map_df = pd.read_excel(costcenter_persona_map_xlsx, sheet_name=costcenter_persona_map_sheet) \
            if costcenter_persona_map_sheet else pd.read_excel(costcenter_persona_map_xlsx)
        map_df = _upper_strip_cols(map_df)
        mp = dict(zip(map_df[map_costcenter_col.upper()], map_df[map_persona_col.upper()]))
        df_hr["COSTCENTER_MANAGEMENT-LEVEL"] = (
            df_hr[cc_u].astype(str) + "_" + df_hr[ml_u].astype(str)
        ).map(_normalize_path)
        df_hr[out_p_u] = df_hr["COSTCENTER_MANAGEMENT-LEVEL"].map(mp)

    df_hr[out_p_u] = df_hr[out_p_u].map(_normalize_path)
    df_hr[brid_u] = df_hr[brid_u].map(_normalize_path)

    # ---------------- COMPARE ----------------
    df_hr["SHD_HAVE_SHARE_DRIVE_SET"] = df_hr[out_p_u].map(shd_map).apply(lambda x: x if isinstance(x, set) else set())
    df_hr["DOES_HAVE_SHARE_DRIVE_SET"] = df_hr[brid_u].map(does_map).apply(lambda x: x if isinstance(x, set) else set())

    comp = df_hr.apply(lambda r: _compare(r["DOES_HAVE_SHARE_DRIVE_SET"], r["SHD_HAVE_SHARE_DRIVE_SET"]), axis=1)
    df_hr["MATCHED_SHARE_DRIVE"] = comp.map(lambda x: x[0])
    df_hr["MISSING_SHARE_DRIVE"] = comp.map(lambda x: x[1])
    df_hr["EXCESS_SHARE_DRIVE"] = comp.map(lambda x: x[2])

    if out_xlsx:
        with pd.ExcelWriter(out_xlsx, engine="openpyxl") as w:
            df_hr.to_excel(w, index=False, sheet_name="HR_SHARE_DRIVE_SHD_vs_DOES")
            df_shd.to_excel(w, index=False, sheet_name="SHD_HAVE_RAW")
            df_does.to_excel(w, index=False, sheet_name="DOES_HAVE_RAW")

    return df_hr


def _cli():
    p = argparse.ArgumentParser(description="Compare SHOULD-HAVE vs DOES-HAVE Share Drive access")
    p.add_argument("--shd-have", required=True)
    p.add_argument("--hr", required=True)
    p.add_argument("--does-have", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--shd-sheet-contains", default=None)
    p.add_argument("--map-xlsx", default=None)
    p.add_argument("--map-sheet", default=None)
    args = p.parse_args()

    build_share_drive_should_vs_does_report(
        shd_have_xlsx=args.shd_have,
        hr_xlsx=args.hr,
        does_have_access_file=args.does_have,
        out_xlsx=args.out,
        shd_sheet_filter_contains=args.shd_sheet_contains,
        costcenter_persona_map_xlsx=args.map_xlsx,
        costcenter_persona_map_sheet=args.map_sheet,
    )


if __name__ == "__main__":
    _cli()
